### PR TITLE
Create genre class

### PR DESCRIPTION
**Pull request by ivangonzalez224**
It is our Catalog of my this project and I added the following features:

Issues related: #12 and #14 

- Created the Genre class.
- Defined the class properties in the constructor.
- Added the add_item method.

### CODE REVIEW

**Review by hajnaloltyan — CHANGES_REQUESTED** [review]
## Hi @ivangonzalez224.

Your project looks great, the only change I would suggest is that in the constructor, the Diagram says **name** and not names. 

After fixing it, it would be ready for approval. 👏👏👏

**Comment by ivangonzalez224** [comment]
@hajnaloltyan I tried to use name as an argument but rubocop did not let me, it suggested to use _name, I do not why, so I used names

**Comment by ivangonzalez224** [comment]
Now it worked, changes done !

**Review by hajnaloltyan — APPROVED** [review]
## Hi @ivangonzalez224, 

Great job making the required changes, your PR is complete, and you can merge it! 👏👏👏

**Pull request merged**
